<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Witness\XBoundObject Version=2.0.3.Dependencies.xml" />
    <None Remove="Witness\XBoundObject Version=2.0.3.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Witness\XBoundObject Version=2.0.3.Dependencies.xml" />
    <EmbeddedResource Include="Witness\XBoundObject Version=2.0.3.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IVSoftware.Portable.Xml.Linq.XBoundObject\IVSoftware.Portable.Xml.Linq.XBoundObject\IVSoftware.Portable.Xml.Linq.XBoundObject.csproj" />
    <ProjectReference Include="..\IVSoftware.WinOS.MSTest.Extensions\IVSoftware.WinOS.MSTest.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
